select * from customer;
#Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue from customer
group by gender;
#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from customer
where discount_applied ="Yes" and purchase_amount>(select avg(purchase_amount) from customer);

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as avg_review from customer
group by item_purchased
order by avg_review desc limit 5;
#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount) as avg_amount from customer
where shipping_type in ( "Standard","Express")
group by shipping_type;
#Q5. Do subscribed customers spend more? Compare average spend and total revenue 
select subscription_status,count(customer_id),avg(purchase_amount) as avg_amt,sum(purchase_amount)  as total_revenue
from customer
group by subscription_status
order by avg_amt,total_revenue desc;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,round(sum(case when  discount_applied ="Yes" then 1 else 0 end )/count(*)*100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
#Q7. Segment customers into New, Returning, and Loyal based on their total 
# number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
    from customer)
    select customer_segment,count(*) as each_segment
    from customer_type
    group by customer_segment
    order by each_segment desc;
#Q8. What are the top 3 most purchased products within each category? 
with item_qty as(
  select category,item_purchased,COUNT(customer_id) AS total_orders,row_number()over(partition by category order by COUNT(customer_id) desc) as rnk
  from customer
  group by category,item_purchased) 
  select rnk,category,item_purchased,total_orders
  from item_qty
  where rnk<=3;
  
#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) AS repeat_buyers from customer
where previous_purchases>5
group by subscription_status;
#Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as revenue from customer
group by age_group
order by revenue desc;